#!/usr/bin/env bash

set -eE -o pipefail

read -r -p "Are you sure? This will overwrite the config files in your home directory. [y/N]: " response
if ! [[ $response =~ [yY] ]]; then
    echo "OK, exiting."
    exit 0
fi

# make sure working directory is 'dots' repo root
cd $(dirname $0)

\cp -rvf .bashrc .bash_aliases .bash_custom .vimrc .Xdefaults ~
mkdir -p ~/bin ~/programs ~/pictures ~/downloads ~/documents
\cp -rfv bin/* ~/bin

if [[ "$1" == "gui" ]]; then
    \cp -vrf walls/ ~/pictures/
    \cp -vrf dunst/ i3blocks/ i3/ gsimplecal/ i3lock/ ~/.config
else
    echo "Not unsyncing gui files, pass \$1='gui'"
fi

cd -
