#!/usr/bin/env bash

# "\w is not a directory" -> you forgot to pass dest param

\cp -rf ~/.bashrc ~/.bash_aliases ~/.bash_custom ~/.config/dunst/ ~/.config/i3blocks/ ~/.config/i3 ~/.config/gsimplecal/ ~/.config/i3lock ~/.vimrc ~/.Xresources ~/programs/scripts/ ~/pictures/walls ~/.ncmpcpp/ ~/.Xdefaults  $1
