#!/usr/bin/env bash

# make sure working directory is 'dots' repo root
\cp -rf .bashrc .bash_aliases .bash_custom .vimrc .Xresources .Xdefaults .ncmpcpp/ ~
\cp -rf dunst/ i3blocks/ i3/ gsimplecal/ i3lock/ ~/.config

mkdir -p ~/bin ~/programs ~/pictures
\cp -rf bin/ ~/bin/
\cp -rf walls/ ~/pictures/
