#!/bin/bash

EXT_IP=$(curl -sSfL ifconfig.co)

icon=""

if [[ $? -eq 0 ]]; then
    # got a valid response
    color="#038c2a"
#    value=$EXT_IP
else
    color="#FF0000"
#    value="Offline"
fi

# echo "<span color='$color'>$icon</span>  $value"
echo "<span color='$color'>$icon</span>"
echo "<span color='$color'>$icon</span>"


# copy the value when you click on it (requires xclip)
# case $BLOCK_BUTTON in
#     3) echo "$IP" | xclip ;;
#     *) echo "$IP" ;;
# esac
