#!/usr/bin/env python3

import urllib.request
import json
import os

cities = [
    [ 'Toronto', 6167865 ],
    [ 'Haliburton', 6942554 ],
]

[city_name, city] = cities[0]

if os.environ.get('BLOCK_BUTTON') == '1':
    os.system("firefox https://www.accuweather.com/en/ca/toronto/m5h/weather-forecast/55488")

key_loc = os.path.dirname(os.path.realpath(__file__)) + '/.owm'
key = ''

try:
    with open(key_loc, 'r') as f:
        key = f.read()
        key = key.strip('\n')
except:
    print("OWM key file error.")
    exit

url=('http://api.openweathermap.org/data/2.5/weather?id=%s&appid=%s' % (city, key))
#print(url)

response = ''
with urllib.request.urlopen(url) as connection:
    response = connection.read()
    # for some reason there are extra characters in the response (encoding issue? all should be UTF-8)
    # only seems to happen in python
    # multiple at the beginning
    response = str(response)
    while (response[0] != '{'):
        response = response[1:]

    # and one at the end
    response = response[:len(response) - 1]

#print(response)

jso = json.loads(response)

temp = jso["main"]["temp"]
temp = int(temp)
# K to C
temp -= 273

temp_icon=''
if temp < 18:
    temp_icon=''
elif temp < 8:
    temp_icon=''
elif temp < -3:
    temp_icon=''

# min width is 3 since "-10" is 3 wide
temp = str(temp)
#while(len(temp) < 3):
#   temp = ' ' + temp 

# possible conditions:
# Thunderstorm 2xx, Drizzle 3xx, Rain 5xx, Snow 6xx, Atmosphere (fog) 7xx, Clear 800, Clouds 80x, Extreme 90x
code = jso["weather"][0]["id"]
code = str(code)

icon=''
color='#FFF400'
if code.startswith('2'):
    icon=''
    color='#FFF426'
elif code.startswith('3') or code.startswith('5'):
    icon=''
    color='#1270B6'
elif code.startswith('6'):
    icon=''
    color='#27AAE2'
elif code.startswith('7') or (code.startswith('8') and code != '800'):
    icon=''
    color='#c1c2c6'
elif code.startswith('90'):
    icon=''
    color='#FFF426'

output='<span color="{}">{}</span>  {}°C  {}'.format(color, icon, str(temp), city_name)
print(output)
print(output)
#print("")
